version: '3'
services: 
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    #volume allows us to copy items into the container when saving stuff locally.
    volumes:
      #ignore the node moldules
      - /app/node_modules
      #copy from . locally to /app on the container
      - .:/app